version: '3.8'
services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - '4000:4000'
    volumes:
      - backend-data:/app/data

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  backend-data: